version: '2'
services:
  session_cache:
    image: memcached
    restart: always
  cache:
    image: redis
    restart: always

  webserver:
    depends_on:
      - cache
      - php
      - session_cache
    image: openresty/openresty:centos-rpm
    ports:
      - "8888:80"
    restart: always
    volumes:
      - "./:/app"
      - "./.vhost/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"
      - "./.vhost/cachemanager.lua:/usr/local/openresty/nginx/conf/cachemanager.lua"
      - "./.vhost/proxy-redis.conf:/usr/local/openresty/nginx/conf/sites-enabled/proxy-redis.conf"
    links:
      - cache
      - php
      - session_cache
  php:
    build: .
    volumes:
      - "./:/app"
      - "~/.ssh:/root/.ssh"
      - "~/.composer:/root/.composer"
      - "./.vhost/php-session.conf:/usr/local/etc/php/conf.d/session.ini"
    depends_on:
      - cache
      - session_cache
    links:
      - cache
      - session_cache

